module.exports = {
  onlyUpdateCollections: ['BuildForm', 'ComponentBuilder', 'ProcessData'],
  files: [
    {loader:{ type: 'route'}, filePath: 'components/FirstTimeSetup/FirstTimeSetup.vue', name: 'setup', path: '/pos-setup' },
    {loader: {type: 'route'}, filePath: 'components/PosCustomer/PosCustomer.vue', name: 'posCustomer', path: '/pos-customer' },
    {loader: {type: 'route'}, filePath: 'components/Customer/CustomerOrder.vue', name: 'posCustomerOrder', path: '/pos-customer-order' },
    {loader: {type: 'route'}, filePath: 'components/OrderHistory/OrderHistory.vue', name: 'OrderHistory', path: '/pos-order-history'},
    {loader: {type: 'route'}, filePath: 'components/posPrinterSetting/posPrinterSettingView.vue', name: 'posPrinterSettingView', path: '/pos-printer-setting' },
    {loader: {type: 'route'}, filePath: 'components/Settings/Settings.vue', name: 'Settings', path: '/pos-settings'},
    {loader: {type: 'route'}, filePath: 'components/Settings/view/viewUser/viewUser.vue', name: 'UserSetting', path: '/pos-view-user'},
    {loader: {type: 'route'}, filePath: 'components/Settings/view/viewTax/viewTax.vue', name: 'TaxSetting', path: '/pos-view-tax'},
    {loader: {type: 'route'}, filePath: 'components/Settings/view/viewPayment/viewPayment.vue', name: 'PaymentSetting', path: '/pos-view-payment'},
    {loader: {type: 'route'}, filePath: 'components/Settings/view/viewGeneral.vue', name: 'GeneralSetting', path: '/pos-view-general'},
    {loader: {type: 'route'}, filePath: 'components/Settings/view/viewCompany.vue', name: 'Company', path: '/pos-view-company'},
    {loader: {type: 'route'}, filePath: 'components/Modifiers/dialogEditPopupModifier/dialogEditPopupModifiers.vue', name: 'Modifier', path: '/pos-modifier'},
    {loader: {type: 'route'}, filePath: 'components/Modifiers/dialogChoosePopupModifier/dialogChoosePopupModifier.vue', name: 'ChooseModifier', path: '/pos-choose-modifier'},
    {loader: {type: 'route'}, filePath: 'components/Payment/Payment.vue', name: 'Payment', path: '/pos-payment'},
    {loader: {type: 'route'}, filePath: 'components/Login/Login.vue', name: 'Login', path: '/pos-login'},
    {loader: {type: 'route'}, filePath: 'components/EditTablePlan/EditTablePlan.vue', name: 'EditTablePlan', path: '/pos-edit-table-plan'},
    {loader: {type: 'route'}, filePath: 'components/EditMenuCard/EditMenuCard.vue', name: 'EditMenuCard', path: '/pos-edit-menu-card'},
    {loader: {type: 'route'}, filePath: 'components/OrderView/Order.vue', name: 'Order', path: '/pos-order/:id?'},
    {loader: {type: 'route'}, filePath: 'components/Dashboard/PosDashboard.vue', name: 'Dashboard', path: '/pos-dashboard'},
    {loader: {type: 'route'}, filePath: 'components/OrderView/delivery/PosOrderDelivery.vue', name: 'posOrderDelivery', path: '/pos-order-delivery'},
    {loader: {type: 'route'}, filePath: 'components/Inventory/Inventory.vue', name: 'Inventory', path: '/pos-inventory'},
    {loader: {type: 'route'}, filePath: 'components/Inventory/InventoryReport.vue', name: 'InventoryReport', path: '/pos-inventory-report'},
    {loader: {type: 'route'}, filePath: 'components/Inventory/InventoryStock.vue', name: 'InventoryStock', path: '/pos-inventory-stock'},
    {loader: {type: 'route'}, filePath: 'components/OtherViews/OrderHistory.vue', name: 'OrderHistory', path: '/pos-order-history'},
    {loader: {type: 'route'}, filePath: 'components/Retail/Order/PosOrderRetail.vue', name: 'Retail', path: '/retail--order' },
    {loader: {type: 'route'}, filePath: 'components/Retail/Order/PosOrderRetail.vue', name: 'RetailRefund', path: '/retail--order-refund' },
    {loader: {type: 'route'}, filePath: 'components/EndOfDay/PosEndOfDayReport.vue', name: 'PosEndOfDayReport', path: '/pos-eod-report'},
    {loader: {type: 'route'}, filePath: 'components/MonthReport/posMonthReportView.vue', name: 'posMonthReportView', path: '/pos-month-report'},
    {loader: {type: 'route'}, filePath: 'components/ReportViews/StaffReportView.vue', name: 'StaffReport', path: '/pos-staff-report'},
    {loader: {type: 'route'}, filePath: 'components/Tutorial/Tutorial.vue', name: 'StaffReport', path: '/pos-tutorial'},
    //
    {loader: {type: 'init' }, path: 'composition/plugin-init.js'},
    {loader: {type: 'vue-singleton'}, path: 'components/Store/Snackbar.vue',},
    {loader: {type: 'vue-singleton'}, path: 'components/EmptyStore.vue',},
    {loader: {type: 'backend-api'}, path: 'backend/dayjs-utils.js', type: 'backend'},
    {loader: {type: 'backend-api'}, path: 'backend/modifier/index.js', type: 'backend'},
    // {loader: {type: 'backend-api'}, path: 'backend/customer/customerSchemaRegister.js', type: 'backend'},
    {loader: {type: 'backend-api'}, path: 'backend/rest-handler.js', type: 'backend'},
    {loader: {type: 'backend-api'}, path: 'backend/get-version/get-version.js', type: 'backend'},
    {loader: {type: 'backend-api'}, path: 'backend/print/print-report/report-index.js', type: 'backend'},
    {loader: {type: 'backend-api'}, path: 'backend/print/print-kitchen/kitchen-printer.js', type: 'backend'},
    {loader: {type: 'backend-api'}, path: 'backend/print/print-entire-receipt/entire-receipt-printer.js', type: 'backend'},
    {loader: {type: 'backend-api'}, path: 'backend/print/test-printer/test-printer.js', type: 'backend'},
    // {loader: {type: 'backend-api'}, path: 'backend/call-system-handler/localhost-handler.js', type: 'backend'},
    // {loader: {type: 'backend-api'}, path: 'backend/call-system-handler/socketio-handler.js', type: 'backend'},
    {loader: {type: 'backend-api'}, path: 'backend/call-system-handler/modem-device-java-handler.js', type: 'backend'},
    {loader: {type: 'backend-api'}, path: 'backend/print/print-utils/virtual-printer.js', type: 'backend'},
    {loader: {type: 'css-loader'}, path: 'style/pos.css'},
    {loader: {type: 'backend-api'}, path: 'backend/initDemoData/initDemoData.js'},
    {loader: {type: 'backend-api'}, path: 'backend/migrate-data/index.js'},
    {loader: {type: 'backend-api'}, path: 'backend/order/index.js'},
    {loader: {type: 'backend-api'}, path: 'backend/inventory/inventory.js'},
    {loader: {type: 'backend-api'}, path: 'backend/online-order/online-order.js'},
    {loader: {type: 'backend-api'}, path: 'backend/rn-bridge/app-rn-bridge.js'},
    {loader: {type: 'backend-api'}, path: 'backend/order-logic/report-init-cms.js'},
    {loader: {type: 'backend-api'}, path: 'backend/commit/index.js'},
    {loader: {type: 'backend-api'}, path: 'backend/customer-screen/customer-socket-handler.js'},
    // {
    //   loader: {
    //     type: 'backend-api'
    //   },
    //   path: 'backend/master-node/index.js'
    // },
    {loader: {type: 'backend-api'}, path: 'backend/demo-data/socket-handler.js'},
    // {
    //   loader: {
    //     type: 'backend-api'
    //   },
    //   path: 'backend/usb-printer/usb-printer.js'
    // },
    {loader: {type: 'i18n'}, path: 'i18n/de.js'},
    {loader: {type: 'i18n'}, path: 'i18n/en.js'},
    {loader: {type: 'i18n'}, path: 'i18n/de-DE.js'},
    {loader: {type: 'i18n'}, path: 'i18n/vn.js'}
  ]
};
