import { editable, orderLayout, loadOrderLayout } from "../pos-ui-shared";
import orderLayoutApi from "../../EditMenuCard/orderLayoutApi";

describe("orderLayout", function() {
  let _loadOrderLayout = orderLayoutApi.loadOrderLayout;
  beforeAll(() => {
    const mockOrderLayout = {
      columns: 2,
      rows: 1,
      categories: []
    };
    orderLayoutApi.loadOrderLayout = jest.fn(() => mockOrderLayout);
  });
  afterAll(() => {
    orderLayoutApi.loadOrderLayout = _loadOrderLayout;
  });
  it("should not fill missing area if editable is false", async () => {
    editable.value = false;
    orderLayout.value = { categories: [] };
    await loadOrderLayout();
    expect(orderLayout.value).toMatchInlineSnapshot(`
      Object {
        "categories": Array [],
        "columns": 2,
        "rows": 1,
      }
    `);
  });
  it("should fill missing area if editable is true", async () => {
    editable.value = true;
    orderLayout.value = { categories: [] };
    await loadOrderLayout();
    expect(orderLayout.value).toMatchInlineSnapshot(`
      Object {
        "categories": Array [
          Object {
            "color": "#FFF",
            "columns": 6,
            "left": 0,
            "name": "",
            "products": Array [
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 0,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 0,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 0,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 0,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 0,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 0,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 1,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 1,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 1,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 1,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 1,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 1,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 2,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 2,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 2,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 2,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 2,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 2,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 3,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 3,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 3,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 3,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 3,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 3,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 4,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 4,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 4,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 4,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 4,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 4,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 5,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 5,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 5,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 5,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 5,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 5,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 6,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 6,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 6,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 6,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 6,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 6,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 7,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 7,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 7,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 7,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 7,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 7,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 8,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 8,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 8,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 8,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 8,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 8,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 9,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 9,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 9,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 9,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 9,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 9,
                "type": "Article",
              },
            ],
            "rows": 10,
            "top": 0,
          },
          Object {
            "color": "#FFF",
            "columns": 6,
            "left": 1,
            "name": "",
            "products": Array [
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 0,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 0,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 0,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 0,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 0,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 0,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 1,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 1,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 1,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 1,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 1,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 1,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 2,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 2,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 2,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 2,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 2,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 2,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 3,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 3,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 3,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 3,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 3,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 3,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 4,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 4,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 4,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 4,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 4,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 4,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 5,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 5,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 5,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 5,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 5,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 5,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 6,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 6,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 6,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 6,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 6,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 6,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 7,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 7,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 7,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 7,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 7,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 7,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 8,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 8,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 8,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 8,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 8,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 8,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 0,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 9,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 1,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 9,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 2,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 9,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 3,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 9,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 4,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 9,
                "type": "Article",
              },
              Object {
                "color": "#F5F5F5",
                "left": 5,
                "name": "",
                "product": Object {
                  "category": null,
                  "groupPrinter": null,
                  "groupPrinter2": null,
                  "id": "",
                  "isDivArticle": null,
                  "isItemNote": null,
                  "isNoPrint": null,
                  "name": "",
                  "price": "",
                  "tax": null,
                  "tax2": null,
                  "type": null,
                },
                "text": "",
                "top": 9,
                "type": "Article",
              },
            ],
            "rows": 10,
            "top": 0,
          },
        ],
        "columns": 2,
        "rows": 1,
      }
    `);
  });
});
